### ISSUE TITLE
Clean up millisats showing up on tracks

### ISSUE THREAD

**Issue by blastshielddown** [wavlake/catalog#147]
Issue most likely comes from catalog query that needs cleaning up

See: https://github.com/wavlake/catalog/blob/main/controllers/artists.js#L49

![Image](https://github.com/wavlake/catalog/assets/77257032/76d4e0a2-e668-4a7b-bc5d-9a3fae2fdfec)

**Comment by joshr4** [comment]
Should we return sats in catalog? or continue returning millisats, and format this in the client?
[mobile client code](https://github.com/wavlake/mobile/blob/d5812590a69d5e0d4633d6202638e332d1862af1/components/SatsEarned.tsx#L19
)
Would be more future proof to return millisats 🚀

**Comment by blastshielddown** [comment]
Yeah I think it makes sense to return results in millisats and just format in the client, gives us more flexibility in the future
