### ISSUE TITLE
[ACCOUNTING] Create Deposit

### ISSUE THREAD

**Issue by joshr4** [wavlake/catalog#278]
- [x] Determine all side effects and add to this issue
- [x] Migrate legacy code to new accounting service controller
- [x] Identify all existing code that uses the legacy endpoint and create a follow up ticket to update the call sites to use the new endpoint

**Comment by blastshielddown** [comment]
Side effects:
- Logs an entry in the `transaction` table with the deposit's details and marks the transaction as `is_pending`
- Generates an invoice and returns that payment request to the client
