### ISSUE TITLE
[ACCOUNTING] Create Invoice

### ISSUE THREAD

**Issue by joshr4** [wavlake/catalog#279]
- [x] Determine all side effects and add to this issue
- [x] Migrate legacy code to new accounting service controller
- [x] Identify all existing code that uses the legacy endpoint and create a follow up ticket to update the call sites to use the new endpoint
- [x] Handle distinct types (Regular invoice, Party mode, Zap)

**Comment by blastshielddown** [comment]
Side effects: This endpoint generates an invoice for a user who wants to send a LN payment to a piece of content. There are actually two separate endpoints for this: one for standard invoices `POST` `/ln/generate-amp-invoice` and one for zap requests `GET` `/zap/create-request`. They are mostly the same, both endpoints take a content id and an amount as arguments (also `metadata` as part of the LNURL payRequest flow in the case of the standard invoice). The zap request logic also stores a copy of the request in the db to later publish as part of the zap receipt once the invoice has been paid.

New implementation will use `POST``/invoice/` and `GET``/invoice/zap` as replacements.

**Comment by joshr4** [comment]
When creating the follow up [ACCOUNTING CLIENT] ticket for this, we need to include updates to the embed player, which calls `generate-amp-invoice`

**Comment by blastshielddown** [comment]
Resolved in https://github.com/wavlake/catalog/pull/404 and https://github.com/wavlake/wavlake.com/pull/523
