### ISSUE TITLE
[ACCOUNTING] Get Withdraw

### ISSUE THREAD

**Issue by joshr4** [wavlake/catalog#284]
- [x] Determine all side effects and add to this issue
~[ ] Migrate legacy code to new accounting service controller~ striking because callback will handle this
- [ ] Identify all existing code that uses the legacy endpoint and create a follow up ticket to update the call sites to use the new endpoint

**Comment by blastshielddown** [comment]
Current side effects:
- This is not a GET request today but a PUT, and the controller checks the status of pending invoices in the db and then updates them if the status has changed in LND.

In the new implementation this GET request will only return the status of the withdrawal as it exists in the db at that moment in time. A separate process will handle updating statuses of pending withdrawls

**Comment by blastshielddown** [comment]
Client call task: https://github.com/wavlake/wavlake.com/issues/374
